{% set name = "runthis-sphinxext" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/runthis-sphinxext/releases/download/{{ version }}/runthis-sphinxext-{{ version }}.tar.gz
  sha256: ecd00b0525c08296845f6442a865fd6c7019e3106bfd2d0e6f990c343ba3157b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - sphinx

test:
  imports:
    - runthis.sphinxext

about:
  home: https://github.com/regro/runthis-sphinxext
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A sphinx extension that adds RunThis code blocks'

extra:
  recipe-maintainers:
    - scopatz
